### ISSUE TITLE
Update UserController

### ISSUE THREAD

**Issue by MichelRogov** [tel-ran-de/Accounting#65]
Do a revision for UserController in following:
 - createUser endpoint should return new UserDto to FE
 - add new endpoint that allows to bump the user from student to teacher by its Id.
 - fix/add tests

**Comment by SabadoshViktor** [comment]
I'm take this issue

**Comment by MichelRogov** [comment]
@SabadoshViktor there is a field above, called `Assignees`, assign your self to this issue
